#!/usr/bin/env python3
"""Generate the ns3-ntn-toolkit custom 3D model set (Wavefront OBJ) for the
NetSimulyzer desktop viewer.

The home-grown NtnNetSimulyzerExporter and NtnSceneRecorder emit a `model` name
per node kind (sat / ue / gateway / uav / haps / ship / aircraft / ris). The
NetSimulyzer desktop app resolves those names to .obj files in its models search
path. This script produces a recognizable low-poly model for each kind plus an
Earth sphere, all as plain text OBJ (no external dependency).

Run:  python3 generate_models.py
Out:  sat.obj ue.obj gateway.obj uav.obj haps.obj ship.obj aircraft.obj
      ris.obj earth.obj  (+ this dir is the NetSimulyzer models drop-in)

Coordinate convention: +Z up, +X east, units = metres at model scale 1. The
recorder/exporter set a per-node display Scale, so absolute size here is nominal.
"""

import math
from pathlib import Path

OUT = Path(__file__).resolve().parent


class Obj:
    """Accumulates vertices/faces and writes an OBJ. Faces are 1-indexed."""

    def __init__(self, name):
        self.name = name
        self.v = []
        self.f = []

    def vert(self, x, y, z):
        self.v.append((x, y, z))
        return len(self.v)  # 1-indexed

    def quad(self, a, b, c, d):
        self.f.append((a, b, c, d))

    def tri(self, a, b, c):
        self.f.append((a, b, c))

    def box(self, cx, cy, cz, sx, sy, sz):
        """Add an axis-aligned box centred at (cx,cy,cz) with half-sizes."""
        x0, x1 = cx - sx, cx + sx
        y0, y1 = cy - sy, cy + sy
        z0, z1 = cz - sz, cz + sz
        p = [self.vert(x0, y0, z0), self.vert(x1, y0, z0), self.vert(x1, y1, z0),
             self.vert(x0, y1, z0), self.vert(x0, y0, z1), self.vert(x1, y0, z1),
             self.vert(x1, y1, z1), self.vert(x0, y1, z1)]
        self.quad(p[0], p[1], p[2], p[3])  # bottom
        self.quad(p[4], p[5], p[6], p[7])  # top
        self.quad(p[0], p[1], p[5], p[4])
        self.quad(p[1], p[2], p[6], p[5])
        self.quad(p[2], p[3], p[7], p[6])
        self.quad(p[3], p[0], p[4], p[7])

    def write(self):
        path = OUT / f"{self.name}.obj"
        with open(path, "w") as fh:
            fh.write(f"# ns3-ntn-toolkit model: {self.name}\n")
            fh.write("# generated by generate_models.py\n")
            fh.write(f"o {self.name}\n")
            for x, y, z in self.v:
                fh.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
            for face in self.f:
                fh.write("f " + " ".join(str(i) for i in face) + "\n")
        return path, len(self.v), len(self.f)


def make_sat():
    o = Obj("sat")
    o.box(0, 0, 0, 0.5, 0.5, 0.5)            # bus
    o.box(-1.6, 0, 0, 1.0, 0.6, 0.04)        # -X solar panel
    o.box(1.6, 0, 0, 1.0, 0.6, 0.04)         # +X solar panel
    o.box(0, 0, 0.7, 0.05, 0.05, 0.3)        # antenna mast
    return o


def make_ue():
    o = Obj("ue")
    o.box(0, 0, 0, 0.18, 0.05, 0.32)         # handset slab
    return o


def make_gateway():
    o = Obj("gateway")
    o.box(0, 0, 0.15, 0.25, 0.25, 0.15)      # pedestal
    # Dish as a shallow tilted polygon fan.
    cx, cy, cz, r = 0.0, 0.0, 0.5, 0.6
    centre = o.vert(cx, cy, cz)
    n = 12
    ring = []
    for i in range(n):
        a = 2 * math.pi * i / n
        ring.append(o.vert(cx + r * math.cos(a), cy + r * math.sin(a), cz + 0.25))
    for i in range(n):
        o.tri(centre, ring[i], ring[(i + 1) % n])
    return o


def make_uav():
    o = Obj("uav")
    o.box(0, 0, 0, 0.25, 0.25, 0.08)         # body
    for dx, dy in ((1, 1), (1, -1), (-1, 1), (-1, -1)):
        o.box(dx * 0.45, dy * 0.45, 0.05, 0.22, 0.05, 0.02)  # arm
        o.box(dx * 0.62, dy * 0.62, 0.10, 0.18, 0.18, 0.02)  # rotor disc
    return o


def make_haps():
    o = Obj("haps")
    # Elongated lenticular hull: a stretched octahedron.
    L, W, H = 2.5, 0.6, 0.4
    tip0 = o.vert(-L, 0, 0)
    tip1 = o.vert(L, 0, 0)
    ring = [o.vert(0, W, 0), o.vert(0, 0, H), o.vert(0, -W, 0), o.vert(0, 0, -H)]
    for i in range(4):
        o.tri(tip0, ring[i], ring[(i + 1) % 4])
        o.tri(tip1, ring[(i + 1) % 4], ring[i])
    return o


def make_ship():
    o = Obj("ship")
    o.box(0, 0, 0, 1.2, 0.35, 0.18)          # hull
    o.box(0.2, 0, 0.3, 0.4, 0.25, 0.18)      # superstructure
    o.box(0.2, 0, 0.6, 0.06, 0.06, 0.18)     # funnel
    return o


def make_aircraft():
    o = Obj("aircraft")
    o.box(0, 0, 0, 1.1, 0.16, 0.16)          # fuselage
    o.box(0, 0, 0, 0.25, 1.4, 0.03)          # main wing
    o.box(-0.95, 0, 0.0, 0.12, 0.5, 0.03)    # tailplane
    o.box(-0.95, 0, 0.2, 0.12, 0.03, 0.25)   # fin
    return o


def make_ris():
    o = Obj("ris")
    o.box(0, 0, 0, 0.9, 0.05, 0.9)           # flat reflecting panel
    o.box(0, -0.12, -0.9, 0.08, 0.12, 0.25)  # mounting post
    return o


def make_earth(segments=24, rings=16, radius=1.0):
    """UV sphere; the recorder/official demo scale it to the real Earth radius."""
    o = Obj("earth")
    top = o.vert(0, 0, radius)
    bot = o.vert(0, 0, -radius)
    grid = []
    for j in range(1, rings):
        theta = math.pi * j / rings
        z = radius * math.cos(theta)
        r = radius * math.sin(theta)
        row = []
        for i in range(segments):
            phi = 2 * math.pi * i / segments
            row.append(o.vert(r * math.cos(phi), r * math.sin(phi), z))
        grid.append(row)
    for i in range(segments):
        o.tri(top, grid[0][i], grid[0][(i + 1) % segments])
        o.tri(bot, grid[-1][(i + 1) % segments], grid[-1][i])
    for j in range(len(grid) - 1):
        for i in range(segments):
            a = grid[j][i]
            b = grid[j][(i + 1) % segments]
            c = grid[j + 1][(i + 1) % segments]
            d = grid[j + 1][i]
            o.quad(a, b, c, d)
    return o


def main():
    builders = [make_sat, make_ue, make_gateway, make_uav, make_haps,
                make_ship, make_aircraft, make_ris, make_earth]
    print(f"{'model':<10} {'verts':>6} {'faces':>6}")
    for b in builders:
        path, nv, nf = b().write()
        print(f"{path.stem:<10} {nv:>6} {nf:>6}")


if __name__ == "__main__":
    main()
